export const ROUTES = {
  DASHBOARD: "/",
  SHOPS: "/shops",
  ADMIN_MY_SHOPS: "/my-shops",
  CREATE_SHOP: "/shops/create",
  LOGIN: "/login",
  ORDER_STATUS: "/order-status",
  ORDERS: "/orders",
  PRODUCTS: "/products",
  COUPONS: "/coupons",
  USERS: "/users",
  TAXES: "/taxes",
  SHIPPINGS: "/shippings",
  SETTINGS: "/settings",
  STORE_SETTINGS: "/vendor/settings",
  STORE_KEEPER: "/vendor/store_keepers",
  CATEGORIES: "/categories",
  ATTRIBUTES: "/attributes",
  ATTRIBUTE_VALUES: "/attribute-values",
  BRANDS: "/brands",
  TAGS: "/tags",
  WITHDRAWS: "/withdraws",
  PROFILE_UPDATE: "/profile-update",
  LOGOUT: "/logout",
  STAFFS: "/staffs",
};
