arrowParens: avoid
bracketSpacing: true
htmlWhitespaceSensitivity: css
insertPragma: false
jsxBracketSameLine: false
jsxSingleQuote: false
printWidth: 88
proseWrap: preserve
quoteProps: as-needed
requirePragma: false
semi: false
singleQuote: true
tabWidth: 2
trailingComma: es5
useTabs: false
